[build]
  publish = "/"
  functions = "netlify/functions"

[functions.blobs]
  store = "word-radar-cache"

[functions."*"]
  timeout = 25

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200