# netlify.toml

# Build settings: where your site and functions are located
[build]
  publish = "/"
  functions = "netlify/functions"

# Configuration for ALL serverless functions.
# The "*" is a wildcard that applies the settings to every function.
[functions."*"]
  # Increase the timeout to 26 seconds.
  timeout = 26

# Redirect rule for Single Page Applications (SPA)
# This ensures that refreshing the page on any sub-path still loads your app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions.blobs]
    # "word-radar-cache" is the name of our store. You can name it anything.
    store = "word-radar-cache"