# netlify.toml

# Build settings: where your site and functions are located
[build]
  publish = "/"
  functions = "netlify/functions"

# --- START OF CORRECTION ---
# This is the main table for general function settings.
[functions]
  # The blobs configuration must be nested under the [functions] table.
  [functions.blobs]
    store = "word-radar-cache"
# --- END OF CORRECTION ---

# This wildcard block for per-function settings is correct and can stay as is.
[functions."*"]
  # Increase the timeout to 26 seconds.
  timeout = 26

# Redirect rule for Single Page Applications (SPA)
# This is also correct.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200