# Corrected and Consolidated netlify.toml

# Build settings
[build]
  publish = "/"
  functions = "netlify/functions"

# --- START OF DEFINITIVE FIX ---
# All function settings are now consolidated here.
[functions]
  # This enables the Blob store service for all functions.
  [functions.blobs]
    store = "word-radar-cache"
  
  # This wildcard applies the timeout setting to every individual function.
  [functions."*"]
    timeout = 26
# --- END OF DEFINITIVE FIX ---

# Redirect rule for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200